plugins:
  - react

parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    arrowFunctions: true
    binaryLiterals: true
    blockBindings: true
    classes: true
    defaultParams: false
    destructuring: true
    experimentalObjectRestSpread: true
    forOf: false
    generators: false
    modules: true
    objectLiteralComputedProperties: true
    objectLiteralDuplicateProperties: false
    objectLiteralShorthandMethods: true
    objectLiteralShorthandProperties: true
    octalLiterals: false
    regexUFlag: false
    regexYFlag: false
    restParams: false
    spread: false
    superInFunctions: false
    templateStrings: true
    unicodeCodePointEscapes: false
    globalReturn: false
    jsx: true
    # End ecmaFeatures as of eslint 0.23.0 [2015-06-15]

env:
  browser: true
  node: true
  es6: true
  mocha: true

